image: ruby:2.4.2
# image: alpine:3.7
# image: docker:stable

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  # - docker info
  # - gem install --no-rdoc --no-ri --no-document bundler
  - cd gitlab-ci/reddit
  - bundle install

build_job:
  stage: build
  # services:
  #   - docker:stable
  #   - docker:dind
  script:
    # - apk add --update --no-cache --virtual tmp libc-dev gcc make musl-dev ruby ruby-dev ruby-rdoc ruby-irb ruby-json ruby-bundler
    # - docker build -t my-docker-image .

test_unit_job:
  stage: test
  services:
  # - ruby:2.4.2
  - mongo:latest
  script:
    # - gem install bigdecimal
    # - gem install test-unit
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: bracnch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
