global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#maksim_demenev'