version: '3.3'
services:

  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
      front_net:
        aliases:
          - mongodb

  ui:
    image: ${USER_NAME}/ui:${SERVVERS}
    ports:
      - ${SERVPORT}:${SERVPORT}/tcp
    networks:
      front_net:
        aliases: 
          - ui

  post:
    image: ${USER_NAME}/post:${SERVVERS}
    networks:
      back_net:
        aliases: 
          - post
      front_net:
        aliases: 
          - post

  comment:
    image: ${USER_NAME}/comment:${SERVVERS}
    networks:
      back_net:
        aliases: 
          - comment
      front_net:
        aliases: 
          - comment

volumes:
  post_db:

networks:
  back_net:
  front_net:
