version: '3'

services:
  fluentd:
    image: ${USER_NAME}/fluentd:latest
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:5.6
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:5.6
    ports:
      - "5601:5601"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - front_net

networks:
  front_net:
