apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: reddit
    component: post
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.post.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.post.internalPort }}
  selector:
    app: reddit
    component: post
    release: {{ .Release.Name }}
