version: '3.3'
services:

  prometheus:
    image: prom/prometheus:v2.1.0
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
      - /tmp/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    network_mode: host

  trickster:
    image: tricksterio/trickster
    restart: always
    network_mode: host
    command:
      - '-config=/etc/trickster/trickster.conf'
      - '-origin=http://localhost:9090'
      - '-log-level=debug'
      - '-origin-type=prometheus'
    ports:
      - '9089:9089'
    volumes:
    - /tmp/trickster.conf:/etc/trickster/trickster.conf:ro

  grafana:
    image: grafana/grafana:5.0.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    network_mode: host

volumes:
  prometheus_data:
  grafana_data:
