---
- name: Install DOCKER
  hosts: all
  gather_facts: no
  become: yes
  tasks:

    - name: install additional packages
      package: name="{{ item }}" state=present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: add docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: install docker
      apt:
        name: ['docker-ce','docker-ce-cli','containerd.io']
        state: present
        update_cache: yes

    - name: adding appuser to docker group
      user:
        name: appuser
        groups: docker
        append: yes

    - name: install docker-machine
      shell: >
        base=https://github.com/docker/machine/releases/download/v0.16.0 &&
        curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine &&
        sudo install /tmp/docker-machine /usr/local/bin/docker-machine

    - name: install gitlab-runner
      shell: >
        wget -O /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64 &&
        chmod +x /usr/local/bin/gitlab-runner

    - name: add file /etc/systemd/system/gitlab-runner.service
      template:
        src: templates/gitlab-runner.service.j2
        dest: /etc/systemd/system/gitlab-runner.service

    - name: copy gce-credentials.json
      copy:
        src: ../../../credentials-docker.json
        dest: /home/appuser/gce-credentials.json
