version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${SERVVERS}
    ports:
      - ${SERVPORT}:${SERVPORT}/tcp
    command: ["puma", "--debug", "-w 2"]
    networks:
      front_net:
        aliases: 
          - ui
  post:
    build: ./post-py
    image: ${USERNAME}/post:${SERVVERS}
    networks:
      back_net:
        aliases: 
          - post
      front_net:
        aliases: 
          - post
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${SERVVERS}
    networks:
      back_net:
        aliases: 
          - comment
      front_net:
        aliases: 
          - comment

volumes:
  post_db:

networks:
  back_net:
  front_net:
