version: '3.3'
services:

  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
      front_net:
        aliases:
          - mongodb

  ui:
    image: ${USERNAME}/ui:${SERVVERS}
    ports:
      - ${SERVPORT}:${SERVPORT}/tcp
    networks:
      front_net:
        aliases: 
          - ui

  post:
    image: ${USERNAME}/post:${SERVVERS}
    networks:
      back_net:
        aliases: 
          - post
      front_net:
        aliases: 
          - post

  comment:
    image: ${USERNAME}/comment:${SERVVERS}
    networks:
      back_net:
        aliases: 
          - comment
      front_net:
        aliases: 
          - comment

  prometheus:
    image: ${USERNAME}/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      front_net:
        aliases: 
          - prometheus

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      front_net:
        aliases: 
          - node-exporter

  mongodb-exporter:
    image: ${USERNAME}/mongodb-exporter:latest
    user: root
    command:
      - '--mongodb.uri=mongodb:27017'
    networks:
      front_net:
        aliases: 
          - mongodb-exporter

  blackbox-exporter:
    image: ${USERNAME}/blackbox_exporter:latest
    user: root
    ports:
      - '9115:9115'
    networks:
      front_net:
        aliases: 
          - blackbox-exporter

  cloudprober:
    image: ${USERNAME}/cloudprober:latest
    networks:
      front_net:
        aliases: 
          - cloudprober

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
